name: x Jira automation Create release
on:
  release:
    types:
      - published

jobs:
  jira-automation:
    name: Issues tracking
    uses: appodeal/devops/.github/workflows/shared-jira-automation-create-release.yml@master
    with:
      github_event: "${{ toJson(github.event) }}"
    secrets: inherit
