name: Admob-sync-app Prod Build and Deploy
on:
  push:
    branches:
      - DO-2271/Build_deploy_workflows

jobs:
  manage_consumers:
    name: Run Admob-sync-app Prod Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Prod Build and Deploy
        run: |
          curl -i -XPOST -u "${{ secrets.USER_APPODEAL_RUNNER }}:${{ secrets.PAT_APPODEAL_RUNNER }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/appodeal/devops/actions/workflows/admob-sync-app-prod-build-deploy.yml/dispatches --data '{"ref": "master"}'
#
